name: FastAPI on Render

services:
  - type: web
    name: cancer-progression-api
    runtime: python310
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: MODEL_PATH
        value: "./catboost_cancer_progression_model.cbm"
      - key: PORT
        value: "8000"
